version: '3.8'

services:
  postgres-dev:
    image: postgres:15
    environment:
      POSTGRES_DB: usufruit_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
